spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/demoonlineshop
    username: demoonlineshop
    password: lost123

  sql:
    init:
      platform: postgres

server:
  port: 8081